#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# Prax release snapshot script
#
# 目的：
# 1) 在 Rora 内持续开发 Prax
# 2) 当版本确认时，将当前 Prax 目录冻结成可追溯快照
#
# 为什么这样设计：
# - 先冻结（snapshot）再发布，能避免“线上版本和本地版本不一致”
# - snapshot 是发布审计点，后续回滚和对账都更容易
# -----------------------------------------------------------------------------

if [[ $# -lt 1 ]]; then
  echo "用法: $0 <version>"
  echo "示例: $0 v0.1.0"
  exit 1
fi

VERSION="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRAX_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RELEASES_DIR="$PRAX_ROOT/releases"
TARGET_DIR="$RELEASES_DIR/$VERSION"

if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "错误: version 必须符合 SemVer 格式，例如 v0.1.0"
  exit 1
fi

mkdir -p "$RELEASES_DIR"

if [[ -d "$TARGET_DIR" ]]; then
  echo "错误: 版本目录已存在: $TARGET_DIR"
  echo "请使用新的版本号，或手动删除后重试。"
  exit 1
fi

mkdir -p "$TARGET_DIR"

# 使用 rsync 冻结版本：
# -a 保留文件属性
# --delete 保证快照目录与源完全一致（避免旧文件污染）
# 排除 releases 本身，防止递归复制
rsync -a --delete \
  --exclude ".git/" \
  --exclude "releases/" \
  "$PRAX_ROOT/" "$TARGET_DIR/"

cat > "$TARGET_DIR/RELEASE.md" <<EOF
# Prax Release $VERSION

- source: $PRAX_ROOT
- created_at: $(date "+%Y-%m-%d %H:%M:%S")
- note: Snapshot generated by scripts/release-prax.sh
EOF

echo "✅ 已生成 Prax 版本快照: $TARGET_DIR"
